#ifndef ENUMS_H
#define ENUMS_H

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum TOOL {PENCIL, ERASER, MOUSE, CIRCLE, TRIANGLE, RECTANGLE};

enum ACTION {NONE, UNDO, CLEAR};

#endif