#ifndef ENUMS_H
#define ENUMS_H

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum TOOL {
    PENCIL, PAINTBRUSH, ERASER, MOUSE, 
    CIRCLE, TRIANGLE, RECTANGLE, PENTAGON, DIAMOND,
    BRING_FRONT, BRING_BACK, 
    ENLARGE, MINIMIZE
};

enum ACTION {NONE, UNDO, REDO, CLEAR};

#endif